# Generated by Django 3.1.7 on 2021-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='memo',
            field=models.CharField(max_length=255, null=True, verbose_name='メモ'),
        ),
    ]
