# Generated by Django 3.1.7 on 2021-04-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
